- lerna.json
- package.json
- packages/carbon-addons-boomerang-react/package.json
- packages/cra-template-boomerang/package.json
- packages/farmer/package.json
- packages/logger-middleware/package.json
- packages/styles/package.json
- packages/utils/package.json
- packages/webapp-spa-server/package.json
**Changed**
- Updated all of the `package.json` configs to be consistent and accurate
> fix: cleanup and standardize package.json

- packages/carbon-addons-boomerang-react/.storybook/preview-body.html
- packages/carbon-addons-boomerang-react/src/components/FeatureHeader/FeatureHeader.js
- packages/carbon-addons-boomerang-react/src/components/FeatureHeader/FeatureHeader.stories.js
- packages/carbon-addons-boomerang-react/src/components/FeatureHeader/_featureHeader.scss
- packages/carbon-addons-boomerang-react/src/components/FeatureHeader/index.js
- packages/carbon-addons-boomerang-react/src/components/FeatureNavTab/_featureNavTab.scss
- packages/carbon-addons-boomerang-react/src/index.js
- packages/carbon-addons-boomerang-react/src/styles/mixins/_utils.scss
- yarn.lock
Changes the implementation for the FeatureHeader slightly. Its just a PoC and not necessarily what we should do. Wanted to see how you felt about it. Might be a bit unnecessary but I think it strikes a balance between good defaults and being flexible for other situations we might encounter. 
**New**
- FeatureHeaderTitle
- FeatureHeaderSubtitle
**Changed**
- FeatureHeader implementation and story
- Small style changes for the FeatureNavTabs
Netlify will have a preview build of it. Should be the last link in its check below.
> Feature plt 4621 new components tim

- packages/carbon-addons-boomerang-react/src/components/MemberBar/_memberBar.scss
**Changed**
- MemberBar Avatar Color
> Change MemberBar Avatar Color

- packages/carbon-addons-boomerang-react/src/components/MemberBar/MemberBar.js
Closes #
{{short description}}
**New**
**Changed**
MembarBar: spread props
**Removed**
> feat: memberbar spread props

- packages/webapp-spa-server/package-lock.json
- packages/webapp-spa-server/package.json
Closes #
ISEEC-1611
**Changed**
webapp spa server dependencies version
> [ISEEC-1611] Update Server dependencies

- packages/utils/package.json
- yarn.lock
Closes #
ISEEC-3224
**Changed**
Updated dependencies on "utils" package so they are consistent with the apps and make "npm install" work normally.
> feat [ISEEC-3224] Update apps to work with node 16

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes #
ISEEC-1636
Tested on Launchpad tag 5.5.150
**New**
**Changed**
- {{change thing}}
**Removed**
> Feat iseec 1636 helmet v4

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes #
{{short description}}
**New**
**Changed**
-  Test GA support - Add new script for webapp-spa-server
**Removed**
> Feat iseec 1950 update web app support ga

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Jira Issue #
https://tools.boomerangplatform.net/jira/console/browse/ISEEC-3329
-introduce helm chart flag to conditionally inject beeheard script into webapp
7.9.49 build in Launchpad to see the script being added to the html head in dev.
> Feat iseec 3329 enable beeheard survey

- packages/webapp-spa-server/.env.local
- packages/webapp-spa-server/README.md
- packages/webapp-spa-server/build/index.html
- packages/webapp-spa-server/build/test.js
- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes ISEEC-2466
Adding support for Instana monitoring in addition to New Relic
**New**
- Support for Instana monitoring
**Changed**
- Some refactoring of how scripts are added
**Removed**
- Run locally w/ the correct env variables set for Instana `INSTANA_REPORTING_URL` and `INSTANA_KEY` and confirm that script is added to the page
- Confirm in an integrated environment w/ env vars being passed through
> feat: add instana support, slight refactoring

- packages/styles/package.json
- packages/styles/src/_platform-overrides.scss
- packages/styles/src/boomerang.scss
Closes #
Update Cookies Preferences button styling
**New**
Created "_platform-overrides.scss" file.
Check if button style changes correctly on dev environment in the apps.
> feat [ISEEC-3713] Update Styles in Each App

- packages/webapp-spa-server/package.json
- yarn.lock
Updating to latest dependencies
> fix: update webapp server dependencies

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes #
Fix issues related to CORS Access Policy
**New**
- Function to check and convert a JSON string
**Changed**
- Cors config
> Fix 3627 cors config env var

- packages/utils/package.json
Closes #
- Issues related to axios version
> fix: axios dependencies

- packages/webapp-spa-server/package.json
- yarn.lock
Closes #
{{short description}}
@LucasGrimauth updated new relic due to security issue
**Changed**
- {{change thing}}
**Removed**
> fix: CVE-2023-36665

- packages/webapp-spa-server/package.json
Closes #
CVE 2024-29041
**New**
**Changed**
- Update version for express on webapp-server `4.18.2 -> 4.19.0`
**Removed**
> Fix CVE 2024 29041 express

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes #
Version: 1.3.0-beta.11
**New**
- Support for IBM Instrumentation
**Changed**
- Env variables for GA
> Feat ibm instrumentation poc

- packages/webapp-spa-server/package.json
- packages/webapp-spa-server/pnpm-lock.yaml
Closes #
CVEs for express, send, body-parser and path-to-regexp
Build: 1.3.2
**New**
**Changed**
- {{change thing}}
**Removed**
> fix: cves for body-parser, express, send and path-to-regexp

- packages/webapp-spa-server/index.js
- packages/webapp-spa-server/package.json
Closes #
Webapp SPA server - errors when handling .css files with MIME check
Version: 1.3.3
**New**
**Changed**
- {{change thing}}
**Removed**
> Fix mimetype css error

- packages/utils/package.json
- packages/utils/src/formatErrorMessage/formatErrorMessage.js
Closes #
Jira Issue: [ICA1-525](https://jsw.ibm.com/browse/ICA1-525)
Build Number: 1.1.2
**Changed**
- Updated formatErrorMessage util to accept different error properties.
> fix: [ICA1-525] Create Team Error Message
